CborAdcCalibrationDataMap = { 2*50(float32 => float32) }

CborAdcChannelConfig = [
  interpolation_method: uint,
  ? calibration_table: CborAdcCalibrationDataMap
]

CborAdcConfig = [
  samples: uint,
  adc_channels_config: [*CborAdcChannelConfig],

  json_config_checksum: uint
]
