CborCanSignalConfig = [
  start_bit: uint,
  size_bits: uint,
  factor: float32,
  offset: float32,
  name: tstr,
  unit: tstr
]

CborCanMessageConfig = [
  frame_id: uint,
  send_interval_ms: int,
  script_path: tstr,

  name: tstr,
  message_size: uint,
  signal_configs: [*CborCanSignalConfig]
]

CborCanChannelConfig = [
  type: uint,
  is_extended_id: bool,
  bus_channel: uint,
  bitrate: uint,
  data_bitrate: uint,
  dbc_file_path: tstr,
  message_configs: [*CborCanMessageConfig]
]

CborCanbusConfig = [
  channel_configs: [0*8 CborCanChannelConfig],
  com_bus_channel: int,

  json_config_checksum: uint
]
