CborSensorMetadataConfig = [
  name: tstr,
  unit: tstr,
  description: tstr
]

CborSensorCalibrationDataMap = { 2*50(float32 => float32) }

CborSensorConfigurationConfig = [
  type: uint,
  sampling_rate_ms: int,
  interpolation_method: uint,
  ? channel: uint,
  connection_string: tstr,
  script_path: tstr,
  ? calibration_table: CborSensorCalibrationDataMap,
  ? expression: tstr
]

CborSensorConfig = [
  id: tstr,
  metadata: CborSensorMetadataConfig,
  configuration: CborSensorConfigurationConfig
]

CborSensorsConfig = [
  sensors: [*CborSensorConfig],

  json_config_checksum: uint
]
